name: Semver Test Workflow
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: get-tag
        with:
          tagRegex: "v(.*)"

      -  run:  echo $GIT_TAG_NAME
      -  run:  echo "${{ steps.get-tag.outputs.tag }}"

      - name: Parse semver string
        id: semver-parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
         input_string: "${{ steps.get-tag.outputs.tag }}"

    #  - name: Use parsed semver
    #    run: echo "v${{ steps.semver-parser.outputs.fullversion }}"

      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      # - name: Setup QEMU
      #   id: qemu
      #   uses: docker/setup-qemu-action@v1.0.1
      #   with:
      #     platforms: linux/amd64,linux/arm/v7,linux/arm64

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1.0.4

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1.8.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     platforms: linux/amd64,linux/arm/v7,linux/arm64
      #     push: true
      #     tags: networkboot/dhcpd:${{ steps.get-tag.outputs.tag }}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
